### ISSUE TITLE
Gerbers from some versions of Eagle render at the wrong scale

### ISSUE THREAD

**Issue by Andrew-Dickinson** [Andrew-Dickinson/photonic-etcher#14]
Example: [gerber_1.zip](https://github.com/Andrew-Dickinson/photonic-etcher/files/13300991/gerber_1.zip) (from Eagle version 7.7.0)

**Comment by errolt** [comment]
Same issue with Eagle 6.6. Could this be an inch vs mm issue?

[Gerber-business_card.zip](https://github.com/Andrew-Dickinson/photonic-etcher/files/14641609/Gerber-business_card.zip)

**Comment by errolt** [comment]
PR https://github.com/Andrew-Dickinson/photonic-etcher/pull/17 should fix this issue.
