### ISSUE TITLE
Invert or Flip doesn't work

### ISSUE THREAD

**Issue by BogdanTheGeek** [Andrew-Dickinson/photonic-etcher#5]
I have tried both the online and offline app, on multiple computers and browsers, I can't get the invert colours or flip board to work. The preview and the output are just a solid colour. I have attached the test files.
[PWM_Generator.zip](https://github.com/Andrew-Dickinson/photonic-etcher/files/9438721/PWM_Generator.zip)

I get these errors in the chrome console:
```
Failed to load resource: the server responded with a status of 404 ()
/site.webmanifest:1 Manifest: Line: 1, column: 1, Syntax error.
/site.webmanifest:1          Failed to load resource: the server responded with a status of 404 ()
DevTools failed to load source map: Could not load content for https://andrew-dickinson.github.io/photonic-etcher/gerber-to-svg.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://andrew-dickinson.github.io/photonic-etcher/pcb-stackup.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

**Comment by Andrew-Dickinson** [comment]
@BogdanTheGeek I've confirmed that for the Gerber files you provided, the invert colors and flip controls result in a blank output. Thanks for the report. I'll take a look and see if I can get to the bottom of it!

**Comment by BogdanTheGeek** [comment]
I used kicad 6 to generate them.

**Comment by Andrew-Dickinson** [comment]
Yep I can see that in the metadata. It looks like KiCad doesn't render Gerbers in the same coordinate "location" that Eagle does, it also appears that when tracespace converts Gerbers to SVG, they don't do any transformations to standardize the coordinate locations. Tracespace does however give a viewbox which is centered on the board (the only reason we can see it at all).

I think being a bit more careful with the SVG viewbox/coordinate handling should fix this up. I've got a prototype right now that seems to fix the invert issue, at least

**Comment by Andrew-Dickinson** [comment]
Okay I believe with the `1.1.3` release I have addressed this issue. Please re-open this issue if you continue to experience this bug, or feel free to open another for any others that you find :)

**Comment by BogdanTheGeek** [comment]
Amazing, thank you!
