### ISSUE TITLE
.photon format

### ISSUE THREAD

**Issue by vanBassum** [Andrew-Dickinson/photonic-etcher#9]
Hello,

I have one of the first photon printers. This one only reads the .photon extension.
Any chance you can support this?

BTW, I tried updating my printer, but it still doesn't support .pws files.

**Comment by Andrew-Dickinson** [comment]
Actually @ruediste just opened a PR for that here: #11 

We'll probably have that merged in the next few days

**Comment by ruediste** [comment]
In the mean time, you can use the [live version of my fork](https://ruediste.github.io/photonic-etcher/)

**Comment by vanBassum** [comment]
Very nice, thanks
